"""Generate docs/TEST_MATRIX.md from reports/master_tests.json (written by pytest).

Executed results come only from the recorder in tests/conftest.py. Boundaries
that could not run in the build environment are listed explicitly as NOT RUN,
never as passed.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

NOT_RUN = {
    "T05": ["live-model: real OpenAI extraction quality on the locked evaluation set (no credentials/budget; api.openai.com blocked)"],
    "T18": ["supabase: publish/rollback against the team's Supabase project"],
    "T19": ["live-source: reproducibility from real cached HPO/Mondo/PubMed captures (hosts blocked)"],
    "T20": ["browser: frontend footer shows the served snapshot ID (Lovable repo)"],
    "T21": ["supabase: effective grants for the actual custom roles", "browser: public bundle contains no secrets (Lovable repo)"],
    "T23": ["browser: real deployed journey at mobile width and by keyboard (no frontend or deployment available)"],
    "T24": ["live-model: shared ledger against real OpenAI usage/billing"],
    "T27": ["live-source: real Mondo SSSOM/HPO annotation mapping for the selected diseases"],
    "T30": ["live-source: real direct and Bright Data captures of approved pages (no credentials; hosts blocked)"],
    "T31": ["live-source: the recorded medRxiv smoke route re-fetched (api.medrxiv.org blocked)"],
    "T33": ["human: the actual hour-one context audit for the chosen real contexts (not started)"],
    "T36": ["live-source: full real HPO release alias index"],
    "T37": ["browser: real Lovable preview/published origins against the deployed Render API"],
    "T38": ["deployment: Render service with read-only Supabase role, readiness and cold start"],
}


def main() -> int:
    data = json.loads((ROOT / "reports" / "master_tests.json").read_text())["results"]
    master = (ROOT / "Rare_Disease_Atlas_Backend_V2.2" / "01_MASTER_PLAN_V2.2.md").read_text()
    titles = {m.group(1): (m.group(2).strip(), m.group(3).strip())
              for m in re.finditer(r"^\| (T\d\d) \| ([^|]+)\|([^|]+)\|", master, re.M)}
    lines = ["# Master acceptance matrix T01-T38", "",
             "Generated by `python scripts/master_report.py` from `reports/master_tests.json`, which pytest writes "
             "from actually executed tests. Boundaries: `offline-fixture` (shared contract fixtures over HTTP), "
             "`offline-unit` (synthetic source-format fixtures and recorded/scripted model responses), "
             "`database-local` (throwaway local PostgreSQL 16, not Supabase), `static-config`, and "
             "`browser-local` (headless Chromium against the local fixture API; see "
             "`reports/browser_cors_check.json`). NOT RUN rows are external gates, not passes.", "",
             "| ID | Test | Executed boundary: result | Not run (external gate) |", "|---|---|---|---|"]
    for n in range(1, 39):
        tid = f"T{n:02d}"
        rows = data.get(tid, [])
        by_boundary: dict[str, list[str]] = {}
        for row in rows:
            by_boundary.setdefault(row["boundary"], []).append(row["outcome"])
        executed = "; ".join(
            f"{b}: {sum(o == 'passed' for o in outs)}/{len(outs)} passed" for b, outs in sorted(by_boundary.items())
        ) or "none"
        if tid == "T37":
            executed += "; browser-local: CORS probe (scripts/browser_cors_check.py)"
        lines.append(f"| {tid} | {titles.get(tid, ('', ''))[0]} | {executed} | {'; '.join(NOT_RUN.get(tid, [])) or '-'} |")
    failed = [r for rows in data.values() for r in rows if r["outcome"] != "passed"]
    lines += ["", f"Recorded test executions: {sum(len(v) for v in data.values())}; non-passing: {len(failed)}."]
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "TEST_MATRIX.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
