"""Build the real pipeline workspace from the team's uploaded captures.

`python -m atlas real-ingest` registers every file listed in the uploaded
`manifest.jsonl` as a recorded capture (target URL, fetch time, status and
SHA-256 are verified against the manifest), then runs the source loaders
offline. Everything produced is *pending*: the disease selection, research
contexts, audit rows, mechanism subgroups and community records are drafts
derived from source records, and none of them is public until a person
accepts it through `review-export`/`review-batch`/`review-import`.

Selection rules (deterministic, source-justified, no memory or keywords):
- genes: the `genes` and `stretch_genes` of the uploaded run config, resolved
  through their HGNC records;
- diseases: Mondo IDs that GenCC associates with those genes with a
  classification other than the non-positive vocabulary, plus Orphanet
  associations with status `Assessed` and a `Disease-causing...` type mapped
  to exactly one Mondo ID by an exact SSSOM mapping, plus Mondo IDs named by a
  drafted community remit. Obsolete Mondo IDs resolve only through a single
  source-provided replacement;
- mechanism subgroups: only where Orphanet's controlled association type
  itself states loss or gain of function.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlsplit

from atlas.hashing import sha256_bytes, stable_id
from atlas.linking.index import AliasIndex
from atlas.models.io import write_jsonl
from atlas.models.records import Entity, ResearchContext, Scope
from atlas.sources import adapters, bulk
from atlas.sources.builders import AdapterOutput, claim, make_assertion, structured_evidence
from atlas.sources.community import AssetImport, OrganizationImport, normalize_imports, web_page
from atlas.sources.fetch import Capture, Fetcher
from atlas.sources.hpo import HpoOntology, build_ic_reference, parse_hpoa
from atlas.sources.mondo import exact_annotation_ids, parse_sssom
from atlas.sources.obo import OboDocument, parse_obo
from atlas.workspace import Workspace

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_DIR = ROOT / "hackathon-claude-repo" / "data"
DRAFT_MARK = "DRAFT generated by the pipeline from source records; NOT verified by a person"


class IngestError(RuntimeError):
    pass


@dataclass
class Uploads:
    data_dir: Path
    rows: list[dict[str, Any]]
    captures: dict[str, Capture] = field(default_factory=dict)  # manifest key -> capture

    def by_key(self, key: str) -> Capture:
        if key not in self.captures:
            raise IngestError(f"upload {key} is missing from the manifest")
        return self.captures[key]

    def by_source(self, source: str) -> list[tuple[dict[str, Any], Capture]]:
        return [(r, self.captures[r["key"] + "|" + r["path"]]) for r in self.rows if r["source"] == source]


def _target(row: dict[str, Any]) -> str:
    # POST searches (NIH RePORTER) share one endpoint URL; the manifest key identifies the request.
    return row["url"] if row.get("method", "GET") == "GET" else f"{row['url']}#{row['key']}"


def register_uploads(ws: Workspace, data_dir: Path) -> Uploads:
    manifest = data_dir / "manifest.jsonl"
    if not manifest.exists():
        raise IngestError(f"{manifest} not found")
    rows = [json.loads(l) for l in manifest.read_text().splitlines() if l.strip()]
    rows = [r for r in rows if r.get("ok") and r.get("path")]
    fetcher = Fetcher(ws.cache, offline=True)
    uploads = Uploads(data_dir, rows)
    inventory = []
    for row in rows:
        body = (data_dir / row["path"]).read_bytes()
        digest = sha256_bytes(body)
        if digest != row["sha256"]:
            raise IngestError(f"{row['path']}: SHA-256 {digest} differs from the manifest {row['sha256']}")
        capture = fetcher.import_recorded_capture(_target(row), "direct", None, row["fetched_at"], int(row["status"]),
                                                  body, {"content-type": row.get("content_type") or ""})
        uploads.captures[row["key"] + "|" + row["path"]] = capture
        uploads.captures.setdefault(row["key"], capture)
        inventory.append({"source": row["source"], "key": row["key"], "path": row["path"], "target": _target(row),
                          "sha256": digest, "fetched_at": row["fetched_at"], "bytes": len(body)})
    ws.stage.mkdir(parents=True, exist_ok=True)
    (ws.stage / "inventory.json").write_text(json.dumps(inventory, indent=2, sort_keys=True))
    return uploads


def _body(ws: Workspace, capture: Capture) -> bytes:
    return capture.body(ws.cache)


def resolve_mondo(mondo: OboDocument, curie: str) -> str | None:
    term = mondo.terms.get(curie)
    if term is None:
        return None
    if not term.is_obsolete:
        return curie
    if len(term.replaced_by) == 1 and term.replaced_by[0] in mondo.terms and not mondo.terms[term.replaced_by[0]].is_obsolete:
        return term.replaced_by[0]
    return None


# Drafted from the captured FamilieSCN2A page. Every quote is located verbatim in the
# canonical page text; ownership and intended scope keep separate evidence.
FAMILIESCN2A_DISEASE = "MONDO:1060245"
FAMILIESCN2A_ORG_QUOTES = [
    "The FamilieSCN2A Foundation is a global leader in sponsoring and funding critical research projects that aim to "
    "increase understanding of the disorders and work toward patient-centered drug development goals.",
]
FAMILIESCN2A_ASSETS = [
    {"id": "asset:familiescn2a-dragonfly", "name": "The DRAGONFLY Study (global patient registry)", "kind": "registry",
     "ownership": "The FamilieSCN2A Foundation, in partnership with the National Organization for Rare Disorders (NORD), "
                  "has launched the DRAGONFLY Study, a Patient Registry with global reach to study SCN2A-related "
                  "disorders (SRDs).",
     "scope": "Observational / Global Patient Registry for SCN2A-Related Disorders",
     "population": "SCN2A-Related Disorders", "relation": "runs"},
    {"id": "asset:familiescn2a-ctrs", "name": "SCN2A Clinical Trial Readiness Study", "kind": "other",
     "ownership": None,
     "scope": "The CTRS was a prospective study that collected data over a one year period to identify the most "
              "effective tools to measure changes in SCN2A patients.",
     "population": "SCN2A patients", "relation": None},
]


def _familiescn2a(ws: Workspace, document, contexts: dict[str, ResearchContext]) -> AdapterOutput:
    def ref(quote: str) -> dict:
        return {"source_document_id": document.id, "quotes": [{"quote": quote, "section_label": None}],
                "record_locator": None, "record_fields": None}

    org = OrganizationImport.model_validate({
        "id": "org:familiescn2a", "name": "FamilieSCN2A Foundation", "official_url": "https://www.scn2a.org/",
        "contact_url": "https://www.scn2a.org/research/clinical-trials-and-research-opportunities/",
        "served_disease_ids": [FAMILIESCN2A_DISEASE], "serves_evidence": [ref(q) for q in FAMILIESCN2A_ORG_QUOTES],
        "verified_by": DRAFT_MARK, "verified_on": "2026-10-03T00:00:00Z"})
    assets = []
    context_id = f"ctx:{FAMILIESCN2A_DISEASE}"
    for a in FAMILIESCN2A_ASSETS:
        assets.append(AssetImport.model_validate({
            "id": a["id"], "name": a["name"], "kind": a["kind"],
            "owner_organization_id": "org:familiescn2a" if a["ownership"] else None,
            "ownership_relation": a["relation"], "ownership_evidence": [ref(a["ownership"])] if a["ownership"] else [],
            "url": "https://www.scn2a.org/research/clinical-trials-and-research-opportunities/",
            "target_context_ids": [context_id], "scope_evidence": [ref(a["scope"])], "materials_url": None,
            "access_terms_text": None, "population_scope": a["population"], "outcome_measures": [], "age_scope": None,
            "genotype_scope": None, "reuse_permission": "unknown", "last_checked_at": "2026-10-03T19:23:00Z",
            "verified_by": DRAFT_MARK, "verified_on": "2026-10-03T00:00:00Z"}))
    (ws.root / "data" / "drafts").mkdir(parents=True, exist_ok=True)
    write_jsonl(ws.root / "data" / "drafts" / "communities.jsonl", [org])
    write_jsonl(ws.root / "data" / "drafts" / "assets.jsonl", assets)
    return normalize_imports(organizations=[org], assets=assets, studies=[], people=[],
                             documents={document.id: document}, contexts=contexts)


def run_real_ingest(ws: Workspace, data_dir: Path = DEFAULT_DATA_DIR) -> dict[str, Any]:
    uploads = register_uploads(ws, data_dir)
    run_config = json.loads(next(data_dir.glob("config_used_*.json")).read_text())
    symbols = list(dict.fromkeys([*run_config.get("genes", []), *run_config.get("stretch_genes", [])]))
    sources, backbone = AdapterOutput(), AdapterOutput()
    summary: dict[str, Any] = {"notes": []}

    # ---- HPO ontology (OBO Graphs JSON) and annotations
    hp_cap = uploads.by_key("file:hpo_json")
    hp_doc_parsed = bulk.parse_obographs(_body(ws, hp_cap))
    ontology = HpoOntology.from_document(hp_doc_parsed, hp_cap.raw_sha256)
    hp_doc = bulk.bulk_document(hp_cap, title="Human Phenotype Ontology (hp.json)", source_kind="ontology",
                                release=hp_doc_parsed.data_version, external_ref="HPO:hp.json")
    hpoa_cap = uploads.by_key("file:phenotype_hpoa")
    hpoa_raw = _body(ws, hpoa_cap).decode("utf-8")
    annotations = parse_hpoa(hpoa_raw, hpoa_cap.raw_sha256)
    hpoa_doc = adapters.hpoa_document(annotations, hpoa_raw, hpoa_cap)
    sources.documents += [hp_doc, hpoa_doc]
    (ws.stage / "hpo_reference.json").write_text(json.dumps({
        "obo_format": "obographs", "obo_raw_sha256": hp_cap.raw_sha256, "obo_document_id": hp_doc.id,
        "hpoa_raw_sha256": hpoa_cap.raw_sha256, "hpoa_document_id": hpoa_doc.id}, indent=2, sort_keys=True))
    reference = build_ic_reference(annotations, ontology)
    summary["hpo"] = {"release": hp_doc_parsed.data_version, "terms": len(ontology.document.terms),
                      "annotation_release": annotations.release, "ic_reference_omim_diseases": reference.disease_count}

    # ---- Mondo
    mondo_cap, sssom_cap = uploads.by_key("file:mondo_obo"), uploads.by_key("file:mondo_sssom")
    mondo = parse_obo(_body(ws, mondo_cap).decode("utf-8"))
    sssom_meta, sssom_rows = parse_sssom(_body(ws, sssom_cap).decode("utf-8"))
    mondo_doc = bulk.bulk_document(mondo_cap, title="Mondo disease ontology (mondo.obo)", source_kind="ontology",
                                   release=mondo.data_version, external_ref="MONDO:mondo.obo")
    sssom_doc = bulk.bulk_document(sssom_cap, title="Mondo mappings (SSSOM)", source_kind="ontology",
                                   release=sssom_meta.get("mapping_date") or mondo.data_version,
                                   external_ref="MONDO:mondo.sssom.tsv")
    sources.documents += [mondo_doc, sssom_doc]

    # ---- HGNC genes
    genes: dict[str, str] = {}
    for symbol in symbols:
        cap = uploads.by_key(f"hgnc:{symbol}")
        out = adapters.hgnc_gene(cap, _body(ws, cap), symbol)
        sources.extend(out)
        for e in out.entities:
            genes[e.id] = e.id
            genes[symbol] = e.id
    by_symbol = {s: genes[s] for s in symbols if s in genes}

    # ---- GenCC and Orphanet -> disease selection
    gencc_cap = uploads.by_key("file:gencc_submissions")
    gencc_doc = bulk.bulk_document(gencc_cap, title="GenCC submissions export", source_kind="curation_database",
                                   release=None, external_ref="GENCC:submissions-export", license="CC0 (GenCC)")
    rows = bulk.gencc_rows_for(_body(ws, gencc_cap).decode("utf-8"), set(by_symbol))
    orpha_cap = uploads.by_key("file:orphadata_genes")
    orpha_release, associations = bulk.orphanet_associations(_body(ws, orpha_cap), set(by_symbol))
    orpha_doc = bulk.bulk_document(orpha_cap, title="Orphadata product 6: genes associated with rare diseases",
                                   source_kind="curation_database", release=orpha_release,
                                   external_ref="ORPHADATA:en_product6", license="CC-BY-4.0")
    sources.documents += [gencc_doc, orpha_doc]
    selection: dict[str, list[str]] = {}
    unresolved: list[str] = []
    resolved_rows = []
    for number, row in rows:
        target = resolve_mondo(mondo, row["disease_curie"])
        if target is None:
            unresolved.append(f"GenCC {row['sgc_id']}: {row['disease_curie']} has no current Mondo term")
            continue
        row = dict(row)
        row["submitted_mondo_curie"] = row["disease_curie"] if target != row["disease_curie"] else ""
        row["disease_curie"] = target  # an obsolete ID resolves only through its single source-provided replacement
        resolved_rows.append((number, row))
        if row["classification_title"] not in adapters.NON_POSITIVE_NATIVE_VALIDITY:
            selection.setdefault(target, []).append(
                f"GenCC {row['sgc_id']}: {row['gene_symbol']} {row['classification_title']} ({row['submitter_title']})")
    orpha_map = bulk.orpha_to_mondo(sssom_rows)
    for a in associations:
        mondos = orpha_map.get(f"ORPHA:{a.orpha_code}", [])
        if a.association_status == "Assessed" and a.association_type.startswith("Disease-causing") and len(mondos) == 1:
            target = resolve_mondo(mondo, mondos[0])
            if target:
                selection.setdefault(target, []).append(
                    f"Orphanet ORPHA:{a.orpha_code}: {a.gene_symbol} — {a.association_type} ({a.association_status})")
    selection.setdefault(FAMILIESCN2A_DISEASE, []).append("Drafted community remit on the captured FamilieSCN2A page")
    diseases = sorted(d for d in selection if d in mondo.terms)

    for mondo_id in diseases:
        entity, mappings = adapters.mondo_disease(mondo_id, mondo, mondo_doc.id, sssom_rows, sssom_doc.id)
        sources.entities.append(entity)
        sources.mappings += mappings
    backbone.extend(bulk.gencc_assertions(gencc_doc, resolved_rows, genes, set(diseases)))
    orpha_out, proposals, unmapped = bulk.orphanet_records(orpha_doc, associations, genes,
                                                            {k: [resolve_mondo(mondo, m) or m for m in v]
                                                             for k, v in orpha_map.items()})
    keep = [a for a in orpha_out.assertions if a.object_id in set(diseases)]
    keep_supports = {s for a in keep for s in a.support_ids}
    orpha_out.assertions = keep
    orpha_out.supports = [s for s in orpha_out.supports if s.id in keep_supports]
    orpha_out.evidence = [e for e in orpha_out.evidence if e.id in {s.evidence_id for s in orpha_out.supports}]
    backbone.extend(orpha_out)
    summary["unmapped_orphanet"] = unmapped
    summary["unresolved_gencc"] = unresolved

    # ---- HPO disease baselines through exact mappings
    phenotypes: dict[str, Entity] = {}
    for mondo_id in diseases:
        backbone.extend(adapters.disease_baseline_rows(mondo_id, sssom_rows, annotations, ontology, hpoa_doc,
                                                       phenotypes, hp_doc.id))
    backbone.entities += sorted(phenotypes.values(), key=lambda e: e.id)

    # ---- GO biological-process annotations (labels need the GO ontology, which was not uploaded)
    go_cap = uploads.by_key("file:go_human_gaf")
    go_doc = bulk.bulk_document(go_cap, title="GO annotations (goa_human.gaf)", source_kind="curation_database",
                                release=None, external_ref="GO:goa_human.gaf", license="CC-BY-4.0")
    sources.documents.append(go_doc)
    backbone.extend(bulk.go_assertions(go_doc, bulk.gaf_rows_for(_body(ws, go_cap), set(by_symbol)), by_symbol, {}))
    summary["notes"].append("GO process labels are unavailable (GO ontology not uploaded); processes show their GO IDs.")

    # ---- NIH RePORTER (deduplicated by application ID)
    seen: set[str] = set()
    for row, cap in uploads.by_source("reporter"):
        projects = [p for p in bulk.reporter_projects(_body(ws, cap)) if str(p["appl_id"]) not in seen]
        seen |= {str(p["appl_id"]) for p in projects}
        backbone.extend(bulk.reporter_records(cap, projects, by_symbol))
        meta = json.loads(_body(ws, cap)).get("meta", {})
        backbone.coverage.append(adapters.coverage(
            "NIH RePORTER", [f"{row['url']} {json.dumps(row.get('meta') or {}, sort_keys=True)}"], cap.fetched_at,
            returned=len(json.loads(_body(ws, cap)).get("results", [])),
            inspected=len(json.loads(_body(ws, cap)).get("results", [])),
            completion="capped" if meta.get("total", 0) > meta.get("limit", 0) else "complete_for_query",
            failure_reason=(f"{meta.get('total')} matching projects, first {meta.get('limit')} retrieved"
                            if meta.get("total", 0) > meta.get("limit", 0) else None)))

    # ---- PubMed (abstract text stays link_only until a person sets a permitted policy)
    pubmed_docs = 0
    for row, cap in uploads.by_source("pubmed"):
        if "efetch" not in row["url"]:
            continue
        ids = parse_qs(urlsplit(row["url"]).query).get("id", [""])[0].split(",")
        out = adapters.pubmed_articles(cap, _body(ws, cap), {pmid: "link_only" for pmid in ids if pmid})
        pubmed_docs += len(out.documents)
        sources.extend(out)

    # ---- medRxiv (latest recorded version pinned; document role awaits a person)
    for row, cap in uploads.by_source("medrxiv"):
        data = json.loads(_body(ws, cap))
        coll = data.get("collection", [])
        if not coll:
            continue
        doi = coll[0]["doi"]
        version = max(str(c.get("version")) for c in coll)
        sources.extend(adapters.medrxiv_preprint(cap, _body(ws, cap), doi, version, public_text_policy="link_only",
                                                 publication_family_id=None, document_role="unclassified"))

    # ---- ClinicalTrials.gov: link conditions only by exact identity aliases of selected diseases
    index = AliasIndex()
    for entity in sources.entities:
        if entity.type == "disease":
            index.add_entity(entity)
    trials: dict[str, tuple[dict, Capture]] = {}
    for row, cap in uploads.by_source("ctgov"):
        for study in bulk.ctgov_studies(_body(ws, cap)):
            trials.setdefault(study["protocolSection"]["identificationModule"]["nctId"], (study, cap))
    linked_trials = 0
    for nct, (study, cap) in sorted(trials.items()):
        protocol = study["protocolSection"]
        conditions = protocol.get("conditionsModule", {}).get("conditions", [])
        keywords = protocol.get("conditionsModule", {}).get("keywords", [])
        cond_map = {}
        for condition in conditions:
            hit = index.lookup(condition, "disease")
            if hit.resolved_id and hit.via in ("identifier", "identity_alias"):
                cond_map[condition] = hit.resolved_id
        named_genes = sorted({by_symbol[t] for t in [*conditions, *keywords] if t in by_symbol})
        if not cond_map and not named_genes:
            continue
        linked_trials += 1
        out = adapters.clinical_trial(cap, json.dumps(study, sort_keys=True).encode(), cond_map)
        backbone.extend(out)
        document = out.documents[0]
        for gene in named_genes:
            symbol = next(s for s, g in by_symbol.items() if g == gene)
            evidence = structured_evidence(
                document, f"{nct}#/protocolSection/conditionsModule/{symbol}",
                [("nct_id", nct), ("named_term", symbol), ("conditions", "; ".join(conditions)),
                 ("keywords", "; ".join(keywords))],
                study_design=protocol.get("designModule", {}).get("studyType") or "not stated")
            claim(backbone, subject_id=nct, predicate="mentions", object_id=gene, context_id=None,
                  scope=Scope(**{**Scope.empty().payload(), "other_qualifiers": [f"Registered condition or keyword: {symbol}"]})
                  if symbol in conditions or symbol in keywords else Scope.empty(),
                  effect_direction="not_applicable", statement_status="listed_record", origin="source_adapter",
                  evidence=evidence)
    for row, cap in uploads.by_source("ctgov"):
        data = json.loads(_body(ws, cap))
        backbone.coverage.append(adapters.coverage(
            "ClinicalTrials.gov", [row["url"]], cap.fetched_at, returned=len(data.get("studies", [])),
            inspected=len(data.get("studies", [])), completion="complete_for_query"))

    # ---- Community page (drafted remit and resources, pending review)
    web_row, web_cap = uploads.by_source("web")[0]
    page = web_page(web_cap, _body(ws, web_cap), title="FamilieSCN2A Foundation: Clinical Trials and Research Opportunities",
                    source_kind="organization_website", public_text_policy="excerpt")
    sources.documents.append(page)

    # ---- Draft research contexts, audit rows and mechanism subgroups
    disease_entities = {e.id: e for e in sources.entities if e.type == "disease"}
    gene_links: dict[str, set[str]] = {}
    for a in backbone.assertions:
        if a.predicate == "gene_associated_with_disease":
            gene_links.setdefault(a.object_id, set()).add(a.subject_id)
    gene_links.setdefault(FAMILIESCN2A_DISEASE, set()).add(by_symbol.get("SCN2A", ""))
    contexts: list[ResearchContext] = []
    audit_rows = []
    hpoa_ids = {r.database_id for r in annotations.rows}
    for mondo_id in diseases:
        entity = disease_entities[mondo_id]
        exact = [r.object_id for r in exact_annotation_ids(mondo_id, sssom_rows)]
        rows_n = sum(1 for r in annotations.rows if r.database_id in exact and r.aspect == "P")
        grouping = "disease_grouping" in mondo.terms[mondo_id].subsets
        cid = f"ctx:{mondo_id}"
        contexts.append(ResearchContext(
            id=cid, gene_ids=sorted(g for g in gene_links.get(mondo_id, set()) if g), disease_id=mondo_id,
            mechanism_id=None, profile_level="disease", label=f"{entity.label} (mechanism unknown)",
            scope=f"All people with {entity.label}; mechanism not specified. A research grouping, not a diagnosis.",
            definition_evidence_ids=[], definition_assertion_ids=[], definition_review_state="pending"))
        audit_rows.append({
            "context_id": cid, "intended_population": f"People with {entity.label}", "mondo_id": mondo_id,
            "source_supported_granularity": "grouping class (Mondo disease_grouping subset)" if grouping else "disease",
            "exact_mapped_ids": exact, "hpo_annotation_rows": rows_n,
            "baseline_available": rows_n > 0 and any(e in hpoa_ids for e in exact),
            "justification_source_ids": sorted({gencc_doc.id, orpha_doc.id} if mondo_id != FAMILIESCN2A_DISEASE
                                               else {page.id}),
            "selection_reasons": selection[mondo_id], "audit_status": DRAFT_MARK})
    for p in proposals:
        if p["disease_id"] not in disease_entities:
            continue
        local = p["disease_id"].replace(":", "-")
        mech_id = f"mech:{p['gene_symbol']}-{p['effect']}-{local}"
        cid = f"ctx:{p['disease_id']}:{p['gene_symbol']}-{p['effect']}"
        scope = Scope(**{**Scope.empty().payload(),
                         "other_qualifiers": [f"Orphanet association type: {p['association_type']}"]})
        assertion = claim(backbone, subject_id=p["disease_id"], predicate="disease_has_mechanism", object_id=mech_id,
                          context_id=cid, scope=scope, effect_direction="not_applicable",
                          statement_status="listed_record", origin="source_adapter", evidence=p["evidence"])
        backbone.entities.append(Entity(
            id=mech_id, type="mechanism", label=f"{p['gene_symbol']} {p['effect']}-of-function ({disease_entities[p['disease_id']].label})",
            aliases=[], external_ids=[],
            properties={"gene_id": p["gene_id"], "functional_effect": p["effect"], "process_ids": [],
                        "cell_tissue_text": None, "assay_species_text": None,
                        "definition_evidence_ids": [p["evidence"].id]},
            identity_source_ids=[orpha_doc.id]))
        contexts.append(ResearchContext(
            id=cid, gene_ids=[p["gene_id"]], disease_id=p["disease_id"], mechanism_id=mech_id,
            profile_level="subgroup",
            label=f"{disease_entities[p['disease_id']].label}, {p['gene_symbol']} {p['effect']}-of-function subgroup",
            scope=f"People with {disease_entities[p['disease_id']].label} and {p['gene_symbol']} variants that "
                  f"Orphanet records as {p['effect']}-of-function.",
            definition_evidence_ids=[p["evidence"].id], definition_assertion_ids=[assertion.id],
            definition_review_state="pending"))
        audit_rows.append({**next(r for r in audit_rows if r["mondo_id"] == p["disease_id"]), "context_id": cid,
                           "intended_population": f"People with {disease_entities[p['disease_id']].label} and "
                                                  f"{p['gene_symbol']} {p['effect']}-of-function variants",
                           "justification_source_ids": [orpha_doc.id]})
    context_map = {c.id: c for c in contexts}
    backbone.extend(_familiescn2a(ws, page, context_map))
    write_jsonl(ws.stage / "drafts" / "contexts.jsonl", contexts)
    (ws.config / "context_mapping_audit.json").write_text(json.dumps(
        {"_comment": "Drafted from source records by `python -m atlas real-ingest`; every row needs the context "
                     "review gate (review-export/review-import) before publication.",
         "status": "draft_generated", "contexts": audit_rows}, indent=2) + "\n")
    (ws.config / "disease_selection.json").write_text(json.dumps(
        {"_comment": "Diseases selected by the deterministic rules in atlas/real_data.py; reasons cite source records.",
         "genes": by_symbol, "diseases": {d: selection[d] for d in diseases}, "unresolved": unresolved,
         "unmapped_orphanet": unmapped}, indent=2) + "\n")
    ws.write_part("sources", sources)
    ws.write_part("backbone", backbone)
    summary.update({
        "genes": len(by_symbol), "diseases": len(diseases), "contexts": len(contexts),
        "mechanism_subgroups": sum(1 for c in contexts if c.mechanism_id), "documents": len(sources.documents) + len(backbone.documents),
        "pubmed_articles": pubmed_docs, "trials_linked": linked_trials, "trials_inspected": len(trials),
        "reporter_projects": len(seen), "assertions": len(backbone.assertions),
        "entities": len(sources.entities) + len(backbone.entities)})
    return summary
